== Gradle Plugin

=== Usage guide

Swagger2Markup provides a Gradle plugin. The Gradle plugin is published in JCenter and Maven Central. Add the following snippet to your Gradle build file:

[source,java]
[source,groovy, subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'io.github.swagger2markup:swagger2markup-gradle-plugin:{project-version}'
    }
}

apply plugin: 'io.github.swagger2markup'
----

The plugin adds a new task named ``convertSwagger2markup``. You can run the task as follows:

`gradlew convertSwagger2markup` 

You can customize the task by configuring a Map of <<Swagger2Markup properties>>.

[source,groovy]
----
convertSwagger2markup {
    swaggerInput file("src/docs/asciidoc")
    markupOutputFile file("${buildDir}/asciidoc")
    config = ['swagger2markup.markupLanguage' : 'ASCCIDOC',
              'swagger2markup.pathsGroupedBy' : 'TAGS']
}

----

[options="header"]
.Gradle Plugin properties
|====
| Name | Description | Type |  Example | Default
| swaggerInput | The directory or file path to the Swagger specification | File | `file("src/docs/swagger_petstore.yaml")` (file) or `file("src/docs/swagger")` (directory) | ``file("src/docs/swagger")`` 
| markupOutputDir | The directory where the output should be stored. | String | `new File("/tmp/asciidoc")` | ``file("$buildDir/asciidoc")`` 
| markupOutputFile | The file (without extensions) where the output should be stored. | String |  ``file("$buildDir/asciidoc/swagger")`` | 
| config | The Swagger2Markup properties to configure the converter | Map |  ['swagger2markup.markupLanguage' : 'ASCCIDOC'] |
|====





